---
title: "Death years"
author: "Scott Olesen"
date: ""
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=7, fig.height=4, 
                      echo=FALSE, warning=FALSE, message=FALSE, cache=TRUE)
```

Do Medicare beneficiaries use a lot of antibiotics in their last year of life? Is it bad to be excluding these people?

```{r load_data}
bene = read_tsv('bene_2011.tsv')
pde = read_tsv('pde_2011.tsv')

na20 = function(x) if_else(is.na(x), 0L, x)

usage = pde %>%
  group_by(bene_id) %>%
  summarize(n_claims=n(), n_days=sum(days_supply)) %>%
  right_join(bene, by='bene_id') %>%
  mutate_at(vars(n_claims, n_days), na20)
```

```{r histograms}
usage %>%
  filter(is.na(death_date)) %>%
  ggplot(aes(x=n_claims)) +
  geom_histogram() +
  scale_y_log10()

usage %>%
  filter(!is.na(death_date)) %>%
  mutate(death_week=week(death_date),
         scaled_n_claims=52/death_week * n_claims) %>%
  ggplot(aes(x=scaled_n_claims)) +
  geom_histogram() +
  scale_y_log10()
```

```{r tables}
nz = function(x) x[x > 0]
fnz = function(x) length(nz(x)) / length(x)

usage %>%
  mutate(died=!is.na(death_date)) %>%
  group_by(died) %>%
  summarize(n_beneficiaries=n(),
            mean_n=mean(n_claims),
            fraction_nonzero=fnz(n_claims),
            nonzero_mean=mean(nz(n_claims))) %>%
  kable
```