---
title: "Ms 1"
author: "Scott Olesen"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='fig/', dev=c('png', 'pdf'),
                      echo=FALSE, warning=FALSE, message=FALSE, cache=TRUE,
                      error=FALSE, autodep=TRUE)
import::from(knitr, kable)
```

# Population characteristics

```{r pop_chars}
pop_chars = read_tsv('tables/pop_chars.tsv') %>%
  select(-sem_age, -sem_n_cc) %>%
  mutate_at(vars(n_female:n_region_midwest), function(x) x / .$n_bene * 100)

trend_p = function(x) tidy(t.test(diff(x)))$p.value

pop_char_trends = pop_chars %>%
  select(year, n_bene, mean_age, mean_n_cc, n_female:n_region_midwest) %>%
  gather('key', 'value', -year) %>%
  arrange(key, year) %>%
  group_by(key) %>%
  summarize(p=trend_p(value)) %>%
  mutate(adj.p=p.adjust(p, method='BH'))

pop_chars %>%
  mutate(n_bene=prettyNum(n_bene, big.mark=',')) %>%
  mutate_at(vars(mean_age, sd_age, n_female:n_region_midwest), function(x) format(x, digits=1, nsmall=1)) %>%
  mutate_at(vars(mean_n_cc, sd_n_cc), function(x) format(x, digits=2, nsmall=2)) %>%
  gather('key', 'value', -year) %>%
  spread(year, value) %>%
  mutate(key=factor(key, levels=names(pop_chars))) %>%
  arrange(key) %>%
  kable(caption='Population characteristics')

pop_char_trends %>%
  kable(caption='Trends in population characteristics')
```

There are `r scan('tables/n_unique_bene.txt') %>% prettyNum(big.mark=',')` unique beneficiaries.

```{r pde_counts}
read_tsv('raw_data/firstfill.tsv') %>%
  group_by(firstfill) %>%
  summarize(n_pde=sum(n_pde)) %>%
  #arrange(desc(firstfill)) %>%
  mutate(cum_n=prettyNum(cumsum(n_pde), big.mark=',')) %>%
  kable(caption='PDEs by firstfill (or refill)')
```

# Trends in drug usage

## Raw trends

```{r raw_drug_trends}
claims_by_abx = read_tsv('tables/claims_by_abx.tsv') %>%
  mutate(abx=fct_inorder(factor(abx)))

abx_levels = levels(claims_by_abx$abx)

claims_by_abx %>%
  filter(abx=='overall') %>%
  ggplot(aes(x=year, y=cpkp)) +
  geom_point() + geom_line() +
  scale_y_continuous(limits=c(975, 1525), breaks=c(1000, 1125, 1250, 1375, 1500)) +
  theme_minimal() +
  ggtitle('Unadjusted consumption, all abx')

claims_by_abx %>%
  filter(abx %in% c('azithromycin', 'ciprofloxacin', 'amoxicillin', 'cephalexin', 'tmpsmx', 'levofloxacin')) %>%
  ggplot(aes(x=year, y=cpkp, color=abx)) +
  geom_point() + geom_line() +
  scale_y_continuous(limits=c(0, 250), breaks=c(0, 50, 100, 150, 200, 250)) +
  theme_minimal() +
  ggtitle('Unadjusted consumption, top 5')

claims_by_abx %>%
  filter(abx %in% c('amoxclav', 'doxycycline', 'nitrofurantoin', 'clindamycin')) %>%
  ggplot(aes(x=year, y=cpkp, color=abx)) +
  geom_point() + geom_line() +
  scale_y_continuous(limits=c(0, 100), breaks=c(0, 50, 100)) +
  theme_minimal() +
  ggtitle('Unadjusted consumption, next 5')
```

## Trends in appropriateness

```{r drug_trends}
est2pct = function(x) (exp(x) - 1)*100

drug_trends = read_tsv('tables/trend_models.tsv') %>%
  filter(term=='year') %>%
  arrange(estimate) %>%
  mutate(estimate=3*estimate,
         std.error=sqrt(3)*std.error) %>%
  mutate(ci=1.96*std.error,
         ci_lo=estimate-ci,
         ci_hi=estimate+ci) %>%
  mutate(y=est2pct(estimate),
         ymin=est2pct(ci_lo),
         ymax=est2pct(ci_hi)) %>%
  mutate(change=sprintf('%.2f (%.2f -- %.2f)', y, ymin, ymax))
```

```{r approp_trends}
# fold change in consumption
pde_trend = drug_trends %>%
  filter(abx=='overall') %>%
  mutate(rr=exp(estimate),
         rr_lo=exp(ci_lo),
         rr_hi=exp(ci_hi))

d_c = pde_trend$rr
d_c_lo = pde_trend$rr_lo
d_c_hi = pde_trend$rr_hi

# fraction inappropriate in 2011
risk_ratio_f = function(or, p) or / (1 + p * (or - 1))
f_i = scan('tables/inapprop_risk_2011.txt')

inapprop_trend = read_tsv('tables/inapprop_trend.tsv') %>%
  filter(term=='year') %>%
  mutate(estimate=3*estimate,
         std.error=sqrt(3)*std.error) %>%
  mutate(ci=1.96*std.error,
         ci_lo=estimate-ci,
         ci_hi=estimate+ci) %>%
  mutate(or   =exp(estimate),
         or_lo=exp(ci_lo),
         or_hi=exp(ci_hi)) %>%
  mutate(rr   =risk_ratio_f(or, f_i),
         rr_lo=risk_ratio_f(or_lo, f_i),
         rr_hi=risk_ratio_f(or_hi, f_i))

d_f = inapprop_trend$rr
d_f_lo = inapprop_trend$rr_lo
d_f_hi = inapprop_trend$rr_hi
  
rr2pct = function(x) round((x - 1) * 100, 2)

inapprop_trends = data_frame(
  abx=c('overall_inapp', 'overall_app'),
  y   =c(d_c    * d_f,    (1.0 - d_f    * f_i) / (1.0 - f_i) * d_c),
  ymin=c(d_c_lo * d_f_lo, (1.0 - d_f_hi * f_i) / (1.0 - f_i) * d_c_lo),
  ymax=c(d_c_hi * d_f_hi, (1.0 - d_f_lo * f_i) / (1.0 - f_i) * d_c_hi)
) %>%
  mutate_if(is.numeric, rr2pct)

kable(inapprop_trends, caption='Percent changes in in/appropriate prescribing')
```

## Adjusted trends

```{r drug_trends_display}
drug_trends %>%
  select(abx, y, ymin, ymax) %>%
  mutate_if(is.numeric, function(x) format(x, digits=2, nsmall=2)) %>%
  kable(caption='Drug trends: Percent change from 2011 to 2014')

abx_trends_levels = drug_trends %>%
  filter(abx != 'overall') %$%
  { c('overall', 'overall_app', 'overall_inapp', rev(abx)) }

drug_and_inapprop_trends = drug_trends %>%
  select(abx, y, ymin, ymax) %>%
  bind_rows(inapprop_trends) %>%
  mutate(abx=factor(abx, levels=rev(abx_trends_levels)))

drug_and_inapprop_trends %>%
  ggplot(aes(x=abx, y=y, ymin=ymin, ymax=ymax)) +
  geom_bar(stat='identity', fill='white', color='black') +
  geom_errorbar(width=0.5) +
  coord_flip() +
  xlab('') +
  ylab('adjusted change in consumption 2011 to 2014 (%)') +
  scale_y_continuous(limits=c(-22, 32), breaks=c(-20, -10, 0, 10, 20, 30)) +
  theme_minimal() +
  theme(axis.title.x = element_text(size=16),
        axis.text = element_text(size=16))

drug_and_inapprop_trends %>%
  arrange(desc(abx)) %>%
  kable(caption='Percent changes; same data as in figure')
```

# Prescribing practice

```{r prescribing_practice}
dx_counts_2011 = read_tsv('raw_data/dx_counts.tsv') %>%
  left_join(select(pop_chars, year, n_bene), by='year') %>%
  mutate(dkpy=round(n_encounter/n_bene*1000)) %>%
  filter(year==2011) %>%
  select(dx_cat, dkpy)

dx_from_pde_2011 = read_tsv('raw_data/dx_from_pde.tsv') %>%
  filter(year==2011) %>%
  mutate(f_with_dx=n_pde_with_encounter/n_pde_with_any_encounter) %>%
  select(antibiotic, dx_cat, year, f_with_dx)

dx_to_pde_table = read_tsv('tables/dx_to_pde_table.tsv') %>%
  select(-n_encounters) %>%
  filter(year %in% c(2011, 2014)) %>%
  gather('abx', 'f_with_abx', azithromycin:clindamycin)

# swo: convert ORs to RRs!
rr2pct = function(x) (x - 1) * 100

dx_to_pde_trends = read_tsv('tables/dx_to_pde_trends.tsv') %>%
  filter(term=='year') %>%
  mutate(estimate=3*estimate,
         std.error=sqrt(3)*std.error) %>%
  mutate(ci=1.96*std.error,
         ci_lo=estimate-ci,
         ci_hi=estimate+ci) %>%
  mutate(or=   exp(estimate),
         or_lo=exp(ci_lo),
         or_hi=exp(ci_hi)) %>%
  left_join(filter(dx_to_pde_table, year==2011), by=c('dx_cat', 'abx')) %>%
  mutate(rr=   risk_ratio_f(or,    f_with_abx),
         rr_lo=risk_ratio_f(or_lo, f_with_abx),
         rr_hi=risk_ratio_f(or_hi, f_with_abx)) %>%
  mutate(y=rr2pct(rr),
         ymin=rr2pct(rr_lo),
         ymax=rr2pct(rr_hi)) %>%
  mutate(change=sprintf('%.2f (%.2f -- %.2f)', y, ymin, ymax)) %>%
  select(dx_cat, abx, change)
```

```{r combined_table}
format2 = function(x) format(round(x, 2), digits=2, nsmall=2)

part1 = dx_counts_2011 %>%
  mutate(dkpy=as.character(dkpy)) %>%
  spread(dx_cat, dkpy) %>%
  mutate(abx='dx', key1='dkpy', key2='')

part2 = dx_from_pde_2011 %>%
  # throw out some rare drugs
  filter(!is.na(dx_cat)) %>%
  mutate(f_with_dx=format2(f_with_dx*100)) %>%
  spread(dx_cat, f_with_dx) %>%
  mutate(key1='pde2dx', key2=as.character(year)) %>% rename(abx=antibiotic)

part3 = dx_to_pde_table %>%
  mutate(f_with_abx=format2(f_with_abx*100)) %>%
  spread(dx_cat, f_with_abx) %>%
  mutate(key1='dx2pde', key2=as.character(year))

part4 = dx_to_pde_trends %>%
  spread(dx_cat, change) %>%
  mutate(key1='dx2pde_trend', key2='')

combined_table = bind_rows(part1, part2, part3, part4) %>%
  mutate(abx=factor(abx, levels=c('dx', abx_levels)),
         key1=factor(key1, levels=c('dkpy', 'pde2dx', 'dx2pde', 'dx2pde_trend'))) %>%
  arrange(abx, key1, key2)
```

## Respiratory

```{r respiratory}
combined_table %>%
  select(abx, key1, key2, pneumonia, sinusitis, uri, bronchitis) %>%
  filter(abx %in% c('dx', 'azithromycin', 'levofloxacin', 'amoxclav')) %>%
  kable
```

# Supplement

## Claims by demography

```{r claims_by_demography}
claims_by = function(by) {
  read_tsv(str_interp("tables/claims_by_${by}.tsv")) %>%
    mutate(group_type=by) %>%
    rename(group=!!rlang::sym(by)) %>%
    filter(year %in% c(2011, 2014)) %>%
    select(group_type, group, year, cpkp) %>%
    spread(year, cpkp) %>%
    mutate_at(vars(`2011`, `2014`), round)
}

trends_by_demography = read_tsv('tables/demography_models.tsv') %>%
  filter(term=='year') %>%
  mutate(estimate=3*estimate,
         std.error=sqrt(3)*std.error) %>%
  mutate(ci=1.96*std.error,
         ci_lo=estimate-ci,
         ci_hi=estimate+ci) %>%
  mutate(y=est2pct(estimate),
         ymin=est2pct(ci_lo),
         ymax=est2pct(ci_hi)) %>%
  mutate(change=sprintf('%.2f (%.2f -- %.2f)', y, ymin, ymax)) %>%
  select(group_type, group, change)

# overall trend row
overall_change = drug_trends %>% filter(abx=='overall') %>% pull(change)
overall_row = claims_by_abx %>%
  filter(abx=='overall', year %in% c(2011, 2014)) %>%
  mutate(cpkp=round(cpkp)) %>%
  spread(year, cpkp) %>%
  mutate(group_type='overall', group='overall', change=overall_change) %>%
  select(group_type, group, `2011`, `2014`, change)

bind_rows(
  claims_by('age_group'),
  claims_by('sex'),
  claims_by('race'),
  claims_by('region')
) %>%
  left_join(trends_by_demography, by=c('group', 'group_type')) %>%
  bind_rows(overall_row, .) %>%
  kable
```

## Other respiratory

```{r other_respiratory}
combined_table %>%
  select(abx, key1, key2, pharyngitis, asthma, other_resp) %>%
  filter(abx %in% c('dx', 'azithromycin', 'levofloxacin', 'amoxclav')) %>%
  kable
```

## UTI

```{r uti}
combined_table %>%
  select(abx, key1, key2, uti, uti_t3) %>%
  filter(abx %in% c('dx', 'ciprofloxacin', 'tmpsmx', 'nitrofurantoin')) %>%
  kable
```

## SSTI

```{r ssti}
combined_table %>%
  select(abx, key1, key2, ssti, ssti_t3) %>%
  filter(abx %in% c('dx', 'cephalexin', 'tmpsmx', 'clindamycin')) %>%
  kable
```
