---
title: "ms2"
author: "Scott Olesen"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=7, fig.height=4, fig.path='fig/',
                      echo=FALSE, warning=FALSE, message=FALSE, cache=TRUE)
```

```{r load_data}
regions = read_tsv('../../db/census-regions/census-regions.tsv') %>%
  select(state, state_abbreviation, region)

total_ineq = read_tsv('data/total_pde.tsv') %>%
  left_join(regions, by='state')
group_ineq = read_tsv('data/group_inequality.tsv')
```

# Aggregate usage correlates with fraction of users

```{r fnz-mean}
ggplot(total_ineq, aes(x=mean, y=fnz, color=region, label=state_abbreviation)) +
geom_point() +
geom_label(nudge_x=0.05) +
xlab('claims per beneficiary') +
ylab('fraction of beneficiaries w/ >= 1 claim')
```

# Inequality among users does not correlate well

```{r nzgini-mean}
ggplot(total_ineq, aes(x=mean, y=nzgini, color=region, label=state_abbreviation)) +
geom_point() +
geom_label(nudge_x=0.05) +
xlab('claims per beneficiary') +
ylab('Gini coefficient among benes. w/ >= 1 claim')
```