---
title: "Consumption and resistance across states"
output:
  html_document:
    fig_height: 4
  pdf_document:
    fig_height: 3
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=7, fig.height=4, fig.path='fig/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```

```{r setup}
library(broom)
library(pander)

gram_negs = c('Escherichia coli', 'Klebsiella pneumoniae',
              'Proteus mirabilis', 'Enterobacter cloacae',
              'Klebisella oxytoca', 'Enterococcus faecium')
gram_poss = c('Coagulase-negative staphylococci',
              'Methicillin-resistant S. aureus (MRSA)',
              'Methicillin-susceptible S. aureus (MSSA)',
              'Streptococcus pneumoniae (non-meningitis)',
              'Staphylococcus aureus')
organisms = c(gram_negs, gram_poss)

consumption_drugs=c('trimethoprim/sulfamethoxazole', 'ciprofloxacin',
                    'levofloxacin', 'ceftriaxone', 'nitrofurantoin',
                    'amoxicillin', 'penicillin', 'doxycycline',
                    'azithromycin')
resistance_drugs=c('trimethoprim-sulfamethoxazole', 'ciprofloxacin',
                   'levofloxacin', 'ceftriaxone', 'nitrofurantoin',
                   'ampicillin', 'penicillin',
                   'tetracycline/doxycycline', 'erythromycin')

consumption_resistance = data_frame(consumption_drug=consumption_drugs,
                                    resistance_drug=resistance_drugs)

# get all bug/drug combos (i.e., all bug/cons drug combos with appropriate res drugs)
bug_drug = expand.grid(bug=organisms,
                       consumption_drug=consumption_drugs,
                       stringsAsFactors=FALSE) %>%
  left_join(consumption_resistance, by='consumption_drug') %>%
  select(bug, consumption_drug, resistance_drug)
```
   
```{r load_data}
coherence = read_tsv('../../../../../antibiogram/analysis/geographic-coherence/coherences.tsv') %>%
  rename(resistance_drug=drug) %>%
  mutate(resistance_drug=tolower(resistance_drug),
         state_coherent=level %in% c('state', 'hrr', 'zipcode')) %>%
  select(bug, resistance_drug, state_coherent)

# Antibiogram data, with individual records
abg = read_tsv('../../../../../antibiogram/data/abg.tsv') %>%
  mutate(drug=tolower(drug)) %>%
  rename(resistance_drug=drug) %>%
  select(bug, resistance_drug, state, percent_susceptible)

# swo> State beneficiary information could be used as control variables
# in regressions
#state_bene = read_tsv('../../bene-consumption/state-bene-2011.tsv') %>%
  #filter(state %in% known_states)

# State-level consumption data
state_consumption = read_tsv('../../bene-consumption/state_usage_2011.tsv') %>%
  rename(consumption_drug=antibiotic) %>%
  select(state, consumption_drug, cpkp, did)

dat = bug_drug %>%
  left_join(abg, by=c('bug', 'resistance_drug')) %>%
  left_join(state_consumption, by=c('state', 'consumption_drug'))
```

```{r run_models}
safe_spearman = function(df, expl) {
  if (dim(df)[1] < 3L) {
    data_frame(estimate=NA, statistic=NA, p.value=NA, method=NA, alternative=NA)
  } else {
    cor.test(df[['mean_sus']], df[[expl]], method='spearman') %>% tidy
  }
}

models = function(df) {
  out = data_frame()
  for (expl in c('cpkp', 'did')) {
    new_rows = safe_spearman(df, expl) %>% 
      mutate(explanatory=expl)
    
    out = bind_rows(out, new_rows)
  }
  out
}

pvalue_stars = function(x) {
  case_when(x < 0.001 ~ '***',
            x < 0.01 ~ '**',
            x < 0.05 ~ '*',
            x < 0.1 ~ 'o',
            TRUE ~ '')
}

res = dat %>%
  group_by(bug, resistance_drug, state) %>%
  summarize(mean_sus=mean(percent_susceptible, na.rm=TRUE)) %>%
  left_join(bug_drug, by=c('bug', 'resistance_drug')) %>%
  left_join(state_consumption, by=c('state', 'consumption_drug')) %>%
  mutate_at(vars(cpkp, did), function(x) if_else(is.na(x), 0, x)) %>%
  group_by(bug, resistance_drug, consumption_drug) %>%
  do(models(.)) %>%
  ungroup %>%
  filter(!is.na(estimate)) %>%
  mutate(adj.p.value=p.adjust(p.value, method='BH'),
         sig=pvalue_stars(adj.p.value)) %>%
  left_join(coherence, by=c('bug', 'resistance_drug')) %>%
  mutate(record_number=1:n(),
         plot_fn=sprintf('plots/%03i.pdf', record_number),
         plot_link=pandoc.link.return(url=plot_fn, text='plot')) %>%
  select(bug, consumption_drug, resistance_drug, state_coherent,
         explanatory, correlation=estimate, p.value,
         adj.p.value, sig,
         plot_fn, plot_link)
```

```{r make_plots}
unlink('plots/*.pdf')

for (i in 1:nrow(res)) {
  row = res[i,]
  
  plot_dat = dat %>%
    filter(bug==row$bug, consumption_drug==row$consumption_drug)
  
  p = plot_dat %>%
    filter(bug==row$bug, consumption_drug==row$consumption_drug) %>%
    ggplot(aes_string(row$explanatory, 'percent_susceptible')) +
    geom_point(shape=1) +
    xlab(row$explanatory) +
    ylab('percent susceptible') +
    theme_minimal()
  
  ggsave(row$plot_fn, plot=p)
}
```

The column `state_coherent` means that the variance in susceptibilities of the bug to the resistance drug reported in antibiograms was significantly improved by dividing the antibiogram records into states. The column `explanatory` is the explanatory variable in the Spearman correlation: either claims per 1,000 people or DID (days of drug per 1,000 people per day).

```{r display_results}
res %>%
  mutate_if(is.numeric, function(x) signif(x, digits=3)) %>%
  select(bug, consumption_drug,
         state_coherent, explanatory, correlation,
         p.value, adj.p.value, sig,
         plot_link) %>%
  kable
```